<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <UseWpf>true</UseWpf>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Brows.Sys.Composition\Brows.Sys.Composition.csproj" />
    <ProjectReference Include="..\Brows.Sys.Win32\Brows.Sys.Win32.csproj" />
  </ItemGroup>
</Project>
